import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./content/header";
import Image from "next/image";
import Footer from "./content/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vercel App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex-1 justify-evenly bg-[#BDBDBD]">
        <div>
          <Header />
        </div>
        <div>{children}</div>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
